/**
 * FitPlan - Egzersiz Veri Tabanı (60+ Kapsamlı Egzersiz)
 * Göğüs, Sırt, Omuz, Biceps, Triceps, Bacak, Baldır, Karın ve Kardiyo
 */

export const EXERCISE_DATABASE = [
  // --- GÖĞÜS (CHEST) ---
  {
    id: 1,
    name: "Bench Press",
    slug: "bench-press",
    muscle: ["Göğüs", "Triceps", "Ön Omuz"],
    equipment: ["Barbell", "Bench"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "8-10",
    rest: "90 saniye",
    gif: "images/bench-press.gif",
    video: "videos/bench-press.mp4",
    description: "Düz sehpada halterle yapılan temel üst gövde itiş egzersizidir. Göğüs kaslarını maksimum gerilimle hedefler.",
    tips: "Kürek kemiklerini geriye ve aşağıya kilitleyin, belde doğal bir kavis bırakın, ayakları yere sağlam basın.",
    execution: "1. Barı göz hizasında kavrayın.\n2. Barı kontrollü şekilde göğüs ucuna indirin.\n3. Dirsekleri kilitlemeden patlayıcı güçle yukarı itin.",
    mistakes: "Dirsekleri 90 derece açarak omuzlara aşırı yük bindirmek, kalçayı sehpadan kaldırmak."
  },
  {
    id: 2,
    name: "Incline Dumbbell Press",
    slug: "incline-dumbbell-press",
    muscle: ["Göğüs", "Ön Omuz", "Triceps"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/incline-dumbbell-press.gif",
    video: "videos/incline-dumbbell-press.mp4",
    description: "30-45 derece eğimli sehpada dambıllarla yapılan üst göğüs odaklı pres hareketi.",
    tips: "Sehpa açısını 30 derecede tutmak ön omuz baskısını azaltır ve üst göğsü izole eder.",
    execution: "1. Dambılları göğüs hizasında tutun.\n2. Nefes vererek dambılları yukarı doğru itin.\n3. Tepe noktada göğsü sıkıp yavaşça indirin.",
    mistakes: "Sehpayı 45 dereceden dik konuma getirmek, dambılları tepede birbirine çarpmak."
  },
  {
    id: 3,
    name: "Dumbbell Fly",
    slug: "dumbbell-fly",
    muscle: ["Göğüs"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/dumbbell-fly.gif",
    video: "videos/dumbbell-fly.mp4",
    description: "Düz sehpada dambıllarla yapılan göğüs açış hareketi. Göğüs liflerini esneterek hacim kazandırır.",
    tips: "Dirseklerinizi hafif bükülü (yay şeklinde) sabit tutun, hareketi omuzdan değil göğüsten hissedin.",
    execution: "1. Kollar yukarıda başlayın.\n2. Göğüs kaslarında derin esneme hissedene kadar kolları yana açın.\n3. Sarılma hareketi yaparak tepeye getirin.",
    mistakes: "Aşırı ağır kilo seçip omuz eklemine zarar vermek, dirsekleri büküp pres hareketine dönüştürmek."
  },
  {
    id: 4,
    name: "Push Up (Şınav)",
    slug: "push-up",
    muscle: ["Göğüs", "Triceps", "Ön Omuz", "Karın"],
    equipment: ["Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/push-up.gif",
    video: "videos/push-up.mp4",
    description: "Klasik vücut ağırlığı şınav hareketi. Göğüs, ön omuz, triceps ve merkez bölgeyi kuvvetlendirir.",
    tips: "Vücut düz bir çizgi halinde olmalı; karın ve kalçayı sıkı tutarak belin çökmesini engelleyin.",
    execution: "1. Plank pozisyonunda başlayın.\n2. Göğsünüz yere 2-3 cm kalana kadar inin.\n3. Avuç içlerinizle yeri iterek başlangıç pozisyonuna dönün.",
    mistakes: "Beli aşağı sarkıtmak, boynu aşırı aşağıya veya yukarıya eğmek."
  },
  {
    id: 5,
    name: "Diamond Push Up",
    slug: "diamond-push-up",
    muscle: ["Triceps", "Göğüs", "Ön Omuz"],
    equipment: ["Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "8-12",
    rest: "75 saniye",
    gif: "images/diamond-push-up.gif",
    video: "videos/diamond-push-up.mp4",
    description: "Eller elmas (üçgen) şeklinde birleştirilerek yapılan, iç göğüs ve triceps odaklı şınav varyasyonu.",
    tips: "Ellerinizi doğrudan göğüs kemiğinin altına yerleştirin ve dirsekleri gövdeye yakın tutun.",
    execution: "1. Başparmak ve işaret parmaklarını birleştirip üçgen yapın.\n2. Kontrollü şekilde göğsü ellere yaklaştırın.\n3. Triceps gücüyle yukarı itin.",
    mistakes: "Dirsekleri yana aşırı açmak, bilek ağrısı varken zorlamak."
  },
  {
    id: 6,
    name: "Dips (Göğüs & Kol)",
    slug: "chest-dips",
    muscle: ["Göğüs", "Triceps", "Ön Omuz"],
    equipment: ["Paralel bar"],
    environment: ["gym", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "8-12",
    rest: "90 saniye",
    gif: "images/dips.gif",
    video: "videos/dips.mp4",
    description: "Paralel barlarda vücut ağırlığıyla yapılan, alt göğüs ve arka kol geliştirici güçlü bir bileşik egzersiz.",
    tips: "Göğsü hedeflemek için gövdenizi 30 derece öne eğin ve dirseklerin hafif yana açılmasına izin verin.",
    execution: "1. Paralel barlarda kendinizi yukarı kaldırın.\n2. Öne hafif eğilerek dirsekler 90 derece olana kadar inin.\n3. Göğüs kaslarınızı sıkarak başlangıç noktasına dönün.",
    mistakes: "Omuz eklemini 90 dereceden fazla aşağı indirerek zorlamak."
  },
  {
    id: 7,
    name: "Dumbbell Floor Press",
    slug: "dumbbell-floor-press",
    muscle: ["Göğüs", "Triceps"],
    equipment: ["Dambıl"],
    environment: ["home", "gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/floor-press.gif",
    video: "videos/floor-press.mp4",
    description: "Yerde sehpa olmadan yapılan güvenli ve etkili göğüs/triceps pres varyasyonu.",
    tips: "Dirsekler yere hafifçe dokunduğunda beklemeden kontrollü şekilde yukarı itin.",
    execution: "1. Sırt üstü yere uzanın, dizleri bükün.\n2. Dambılları göğüs hizasından yukarı itin.\n3. Dirsekler yere hafifçe temas edene kadar indirin.",
    mistakes: "Dirsekleri yere sertçe çarpmak."
  },

  // --- SIRT (BACK) ---
  {
    id: 8,
    name: "Pull Up (Barfiks)",
    slug: "pull-up",
    muscle: ["Sırt", "Biceps", "Ön kol"],
    equipment: ["Barfiks demiri"],
    environment: ["gym", "home", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "6-10",
    rest: "90 saniye",
    gif: "images/pull-up.gif",
    video: "videos/pull-up.mp4",
    description: "Geniş tutuşla yapılan kanat ve sırt genişletici en temel üst vücut çekiş hareketidir.",
    tips: "Hareketi kollarla değil, kürek kemiklerini aşağı çekerek ve dirsekleri kalçaya doğru yönlendirerek başlatın.",
    execution: "1. Omuz genişliğinden biraz açık tutuşla bara asılın.\n2. Çeneniz bar hizasını geçene kadar kendinizi çekin.\n3. Yavaşça başlangıç pozisyonuna inin.",
    mistakes: "Bacakları sallayarak ivme kazanmak (kipping), tam hareket aralığını kullanmamak."
  },
  {
    id: 9,
    name: "Chin Up (Ters Barfiks)",
    slug: "chin-up",
    muscle: ["Sırt", "Biceps"],
    equipment: ["Barfiks demiri"],
    environment: ["gym", "home", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "strength",
    sets: 3,
    reps: "6-10",
    rest: "90 saniye",
    gif: "images/chin-up.gif",
    video: "videos/chin-up.mp4",
    description: "Avuç içleri yüze bakacak şekilde yapılan, sırt ve biceps kaslarını aynı anda yoğun çalıştıran hareket.",
    tips: "Biceps odaklı kuvvet kazanımı için göğsü bara doğru yaklaştırın.",
    execution: "1. Dar tutuşla avuçlar yüze bakacak şekilde asılın.\n2. Kendinizi kontrollü şekilde yukarı çekin.\n3. Tepe noktada biceps ve sırtı sıkıp yavaşça inin.",
    mistakes: "Aşağı inişte kontrolsüz şekilde kendini serbest bırakmak."
  },
  {
    id: 10,
    name: "Barbell Bent-Over Row",
    slug: "barbell-row",
    muscle: ["Sırt", "Biceps", "Arka Omuz"],
    equipment: ["Barbell"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "8-10",
    rest: "90 saniye",
    gif: "images/barbell-row.gif",
    video: "videos/barbell-row.mp4",
    description: "Eğilerek halter çekiş hareketi; sırt kalınlığı ve lat gelişimi için altın standarttır.",
    tips: "Gövdeyi yere 45 derecelik açıda sabitleyin, omurgayı nötr tutun, barı göbek deliğine doğru çekin.",
    execution: "1. Dizleri hafif büküp kalçayı geriye vererek eğilin.\n2. Barı karın boşluğuna doğru çekin.\n3. Kürek kemiklerini birbirine sıkıştırıp yavaşça indirin.",
    mistakes: "Sırtı kamburlaştırmak, gövdeyi yukarı zıplatarak ağırlığı savurmak."
  },
  {
    id: 11,
    name: "Dumbbell Single-Arm Row",
    slug: "dumbbell-row",
    muscle: ["Sırt", "Biceps"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/dumbbell-row.gif",
    video: "videos/dumbbell-row.mp4",
    description: "Tek kolla sehpaya destek alınarak yapılan, sağ ve sol sırt kas dengesizliğini gideren çekiş egzersizi.",
    tips: "Dambılı yukarı değil, cebe (kalçaya) doğru çekerek lat kasını maksimum aktive edin.",
    execution: "1. Bir dizinizi ve elinizi sehpaya koyun.\n2. Serbest eldeki dambılı kalça hizasına doğru çekin.\n3. Sırt kasını sıkıp kontrollü indirin.",
    mistakes: "Gövdeyi aşırı döndürerek ivme kazanmak."
  },
  {
    id: 12,
    name: "Lat Pulldown",
    slug: "lat-pulldown",
    muscle: ["Sırt", "Biceps"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 4,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/lat-pulldown.gif",
    video: "videos/lat-pulldown.mp4",
    description: "Makaralı sistemde yukarıdan aşağıya bar çekilerek kanat kaslarının izole edildiği egzersiz.",
    tips: "Barı enseye değil, üst göğüs kemiğine doğru çekin; gövdenizi aşırı geriye yatırmayın.",
    execution: "1. Geniş tutuşla oturun, dizleri sabitleyin.\n2. Barı üst göğse doğru çekin, dirsekleri aşağı bastırın.\n3. Kollar açılırken lat kaslarının esnemesine izin verin.",
    mistakes: "Barı ense arkasına indirmek (omuz sakatlığı riski), geriye aşırı yatmak."
  },
  {
    id: 13,
    name: "Seated Cable Row",
    slug: "seated-cable-row",
    muscle: ["Sırt", "Arka Omuz", "Biceps"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/seated-cable-row.gif",
    video: "videos/seated-cable-row.mp4",
    description: "Oturarak kablo ile karna çekiş hareketi; orta sırt, romboid ve trapez kaslarını güçlendirir.",
    tips: "Çekiş anında göğsü öne çıkarın ve kürek kemiklerini arkada birleştirin.",
    execution: "1. V-tutacağı kavrayın, sırtı dik tutun.\n2. Dirsekleri vücudun yanından geriye çekin.\n3. Tepe noktada 1 saniye bekleyip yavaşça bırakın.",
    mistakes: "Beli bükerek öne-arkaya sallanmak."
  },
  {
    id: 14,
    name: "Inverted Row (Avustralya Barfikisi)",
    slug: "inverted-row",
    muscle: ["Sırt", "Biceps", "Arka Omuz"],
    equipment: ["Barfiks demiri", "Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "strength",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/inverted-row.gif",
    video: "videos/inverted-row.mp4",
    description: "Alçak bar veya sağlam bir masa altında vücut ağırlığıyla yatay çekiş hareketi.",
    tips: "Vücudu topuklardan başa kadar tek bir tahta gibi düz tutun.",
    execution: "1. Alçak barın altına yatın, barı omuz genişliğinde tutun.\n2. Göğsü bara değecek kadar çekin.\n3. Yavaşça başlangıç pozisyonuna dönün.",
    mistakes: "Kalçayı aşağı sarkıtmak."
  },
  {
    id: 15,
    name: "Deadlift",
    slug: "deadlift",
    muscle: ["Sırt", "Hamstring", "Kalça", "Core"],
    equipment: ["Barbell"],
    environment: ["gym"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "5-6",
    rest: "120 saniye",
    gif: "images/deadlift.gif",
    video: "videos/deadlift.mp4",
    description: "Yerden halter kaldırma; tüm arka zinciri (sırt, bel, hamstring, kalça) maksimum çalıştıran kral harekettir.",
    tips: "Barı kaval kemiğine ve bacaklara yakın tutun, hareketi kalça itişiyle tamamlayın.",
    execution: "1. Bar ayağın ortasında dururken eğilin.\n2. Sırtı düzleştirip göğsü kaldırın.\n3. Yeri topuklarla iterek dik konuma gelin.",
    mistakes: "Omurgayı bükerek sırtı yuvarlamak (ağır sakatlık riski)."
  },

  // --- OMUZ (SHOULDERS) ---
  {
    id: 16,
    name: "Overhead Barbell Press (OHP)",
    slug: "overhead-press",
    muscle: ["Omuz", "Triceps", "Üst Göğüs", "Core"],
    equipment: ["Barbell"],
    environment: ["gym"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "6-8",
    rest: "90 saniye",
    gif: "images/overhead-press.gif",
    video: "videos/overhead-press.mp4",
    description: "Ayakta halterin baş üstüne preslenmesi; omuz kuvvetinin ve genel gövde stabilitesinin temel testidir.",
    tips: "Kalça ve karın kaslarını kilitleyin, bar çeneyi geçerken başı hafifçe öne doğru alın.",
    execution: "1. Barı köprücük kemiği üzerinde tutun.\n2. Patlayıcı güçle baş üstüne doğru itin.\n3. Tepe noktada kolları kilitleyip kontrollü indirin.",
    mistakes: "Aşırı bel kavisi vermek, geriye doğru yatmak."
  },
  {
    id: 17,
    name: "Dumbbell Shoulder Press",
    slug: "dumbbell-shoulder-press",
    muscle: ["Omuz", "Triceps"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "8-12",
    rest: "75 saniye",
    gif: "images/dumbbell-shoulder-press.gif",
    video: "videos/dumbbell-shoulder-press.mp4",
    description: "Sehpada oturarak dambıllarla yapılan baş üstü itiş; omuz başlarını hacimlendirir.",
    tips: "Dambılları kulak hizasından başlatıp baş üstünde yay çizerek birleştirin.",
    execution: "1. Dambılları omuz hizasında kavrayın.\n2. Nefes vererek dambılları yukarı doğru itin.\n3. Yavaşça kulak hizasına kadar indirin.",
    mistakes: "Ağırlıkları tepede sertçe birbirine vurmak."
  },
  {
    id: 18,
    name: "Lateral Raise (Yana Açış)",
    slug: "lateral-raise",
    muscle: ["Omuz"],
    equipment: ["Dambıl"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 4,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/lateral-raise.gif",
    video: "videos/lateral-raise.mp4",
    description: "Dambılları yana açarak yan omuz kasını (lateral deltoid) hedefleyen, omuzları geniş gösteren hareket.",
    tips: "Dirsekleri hafif bükün; bilekleri değil dirsekleri yukarı kaldırın. Sürahiyle su doldurur gibi serçe parmağı hafif yukarıda tutun.",
    execution: "1. Dambılları yanlarda tutun.\n2. Omuz hizasına kadar kollarınızı yana doğru açın.\n3. 1 saniye tepe noktada tutup yavaşça indirin.",
    mistakes: "Gövdeyi sallayarak ivmeyle kaldırmak, omuz hizasından çok yukarı çıkarmak."
  },
  {
    id: 19,
    name: "Face Pull",
    slug: "face-pull",
    muscle: ["Arka Omuz", "Sırt", "Trapez"],
    equipment: ["Kablo/Makine", "Direnç bandı"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/face-pull.gif",
    video: "videos/face-pull.mp4",
    description: "Halat tutacakla yüze doğru çekiş; arka omuz, rotator manşet ve duruş (postür) sağlığı için vazgeçilmezdir.",
    tips: "Halat uçlarını burnunuza doğru çekerken ellerinizi iki yana açarak dış rotasyon yapın.",
    execution: "1. Kabloyu göz hizasına ayarlayın.\n2. Halatı alına doğru çekerken dirsekleri yüksek tutun.\n3. Arka omuzları sıkıştırıp yavaşça bırakın.",
    mistakes: "Dirsekleri aşağı düşürmek, sadece biceps ile çekmek."
  },
  {
    id: 20,
    name: "Pike Push Up",
    slug: "pike-push-up",
    muscle: ["Omuz", "Triceps", "Üst Göğüs"],
    equipment: ["Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "8-12",
    rest: "60 saniye",
    gif: "images/pike-push-up.gif",
    video: "videos/pike-push-up.mp4",
    description: "Kalçayı yukarı kaldırarak V şeklinde yapılan ve omuz kaslarını vücut ağırlığıyla geliştiren hareket.",
    tips: "Başınızı ellerin hafif ilerisine doğru üçgen oluşturacak şekilde indirin.",
    execution: "1. Kalçayı kaldırıp ters V pozisyonu alın.\n2. Başınızı yere doğru kontrollü indirin.\n3. Omuzlarınızla yeri iterek tekrar yükselin.",
    mistakes: "Hareketi standart şınava dönüştürmek, kalçayı aşağı indirmek."
  },
  {
    id: 21,
    name: "Arnold Press",
    slug: "arnold-press",
    muscle: ["Omuz", "Triceps"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/arnold-press.gif",
    video: "videos/arnold-press.mp4",
    description: "Dambılların rotasyonla yukarı itildiği, omuzun tüm başlarını aktive eden klasik egzersiz.",
    tips: "Dönüş hareketini akıcı yapın; dambıllar göğüs önünden dönerken yukarıya doğru uzansın.",
    execution: "1. Avuçlar yüze dönük şekilde dambılları göğüste tutun.\n2. İterken bilekleri dışa döndürün.\n3. Tepe noktada kollar yukarıda, avuçlar karşıya baksın.",
    mistakes: "Rotasyonu ağırlığı savurarak kontrolsüzce yapmak."
  },

  // --- BICEPS ---
  {
    id: 22,
    name: "Barbell Biceps Curl",
    slug: "barbell-curl",
    muscle: ["Biceps", "Ön kol"],
    equipment: ["Barbell"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "8-10",
    rest: "60 saniye",
    gif: "images/barbell-curl.gif",
    video: "videos/barbell-curl.mp4",
    description: "Düz veya EZ bar ile yapılan en temel pazu geliştirici kitle hareketidir.",
    tips: "Dirseklerinizi gövdenizin yanına sabitleyin; beli geriye atarak sallanmayın.",
    execution: "1. Barı omuz genişliğinde kavrayın.\n2. Dirsekleri oynatmadan barı göğse doğru bükün.\n3. Tepe noktada biceps kasını sıkıp yavaşça indirin.",
    mistakes: "Belden güç alarak ağırlığı sallamak, dirsekleri öne doğru kaçırmak."
  },
  {
    id: 23,
    name: "Dumbbell Hammer Curl",
    slug: "hammer-curl",
    muscle: ["Biceps", "Ön kol"],
    equipment: ["Dambıl"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/hammer-curl.gif",
    video: "videos/hammer-curl.mp4",
    description: "Avuç içleri birbirine bakacak şekilde (nötr tutuş) yapılan, brachialis ve ön kol kasını kalınlaştıran hareket.",
    tips: "Kolun yan tarafındaki kası hedefleyerek kollara daha kalın bir görünüm kazandırır.",
    execution: "1. Dambılları çekiç tutuşuyla yanlarda tutun.\n2. Dirsekleri sabit tutarak yukarı bükün.\n3. Tepe noktada sıkıp yavaşça indirin.",
    mistakes: "Ağırlığı hızlıca bırakarak negatif fazı atlamak."
  },
  {
    id: 24,
    name: "Incline Dumbbell Curl",
    slug: "incline-curl",
    muscle: ["Biceps"],
    equipment: ["Dambıl", "Bench"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/incline-curl.gif",
    video: "videos/incline-curl.mp4",
    description: "Eğimli sehpada geriye yaslanarak yapılan, biceps uzun başını maksimum esneten ve tepe noktasını (peak) geliştiren hareket.",
    tips: "Kolların arkaya doğru sarkmasına izin vererek derin esneme sağlayın.",
    execution: "1. 45 derece eğimli sehpaya oturun.\n2. Kollar sarkıkken dambılları yukarı doğru bükün.\n3. Tepe noktada çevirip sıkın ve yavaşça indirin.",
    mistakes: "Omuzları öne doğru fırlatmak."
  },
  {
    id: 25,
    name: "Resistance Band Curl",
    slug: "band-curl",
    muscle: ["Biceps", "Ön kol"],
    equipment: ["Direnç bandı"],
    environment: ["home", "outdoor", "gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "45 saniye",
    gif: "images/band-curl.gif",
    video: "videos/band-curl.mp4",
    description: "Direnç bandına basılarak yapılan, hareketin sonuna doğru artan gerilimle pazu liflerini yakan ev dostu egzersiz.",
    tips: "Bandı ayağınızın altında sabitleyin ve dirsekleri gövdeye yapıştırın.",
    execution: "1. Bandın ortasına basın, uçlarını kavrayın.\n2. Tepe noktaya kadar çekip 1 saniye bekleyin.\n3. Dirence karşı koyarak yavaşça bırakın.",
    mistakes: "Bandın gevşek kalarak gerilim kaybetmesi."
  },

  // --- TRICEPS ---
  {
    id: 26,
    name: "Triceps Rope Pushdown",
    slug: "triceps-pushdown",
    muscle: ["Triceps"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/triceps-pushdown.gif",
    video: "videos/triceps-pushdown.mp4",
    description: "Halat aparatıyla makarada aşağı itiş; arka kolun dış ve lateral başını mükemmel izole eder.",
    tips: "Aşağıda halat uçlarını birbirinden ayırarak triceps kasını kilit noktada ekstra sıkın.",
    execution: "1. Dirsekleri kaburgalara sabitleyin.\n2. Halatı aşağı doğru itin ve kollar düzleşince yana açın.\n3. Yavaşça 90 dereceye kadar dönün.",
    mistakes: "Dirsekleri öne-arkaya sallamak, omuzları kaldırmak."
  },
  {
    id: 27,
    name: "Skull Crusher (Alna Triceps Pres)",
    slug: "skull-crusher",
    muscle: ["Triceps"],
    equipment: ["Barbell", "Bench"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/skull-crusher.gif",
    video: "videos/skull-crusher.mp4",
    description: "Yatarak alına veya başın arkasına bar indirilerek yapılan harika bir arka kol kütle hareketi.",
    tips: "Dirseklerinizi birbirine paralel tutun; dışa doğru açılmalarına izin vermeyin.",
    execution: "1. Düz sehpaya uzanın, EZ barı göğüs üstünde tutun.\n2. Sadece dirsekleri bükerek barı alna doğru indirin.\n3. Triceps gücüyle kolları başlangıç konumuna getirin.",
    mistakes: "Ağırlığı hızlıca alna doğru düşürmek, dirsekleri aşırı açmak."
  },
  {
    id: 28,
    name: "Overhead Dumbbell Triceps Extension",
    slug: "overhead-triceps-extension",
    muscle: ["Triceps"],
    equipment: ["Dambıl"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/overhead-triceps.gif",
    video: "videos/overhead-triceps.mp4",
    description: "Baş arkasında tek veya çift elle dambıl indirilerek yapılan, arka kolun uzun başını esneten hareket.",
    tips: "Kolları başın yanına sabitleyin ve dirseklerin sabit bir menteşe gibi çalışmasını sağlayın.",
    execution: "1. Dambılı iki elle baş arkasında tutun.\n2. Dirsekleri bükerek dambılı ensenize doğru indirin.\n3. Kollar düzelene kadar yukarı itin.",
    mistakes: "Dirseklerin yana aşırı kayması."
  },
  {
    id: 29,
    name: "Bench Dips",
    slug: "bench-dips",
    muscle: ["Triceps", "Ön Omuz"],
    equipment: ["Bench", "Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "strength",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/bench-dips.gif",
    video: "videos/bench-dips.mp4",
    description: "Eller sehpa veya sandalyeye konularak yapılan pratik ve etkili bir vücut ağırlığı arka kol hareketi.",
    tips: "Sırtınızı sehpaya yakın tutun; öne doğru kaymayın.",
    execution: "1. Elleri kalça yanında sehpaya koyun, ayakları uzatın.\n2. Dirsekler 90 derece olana kadar kalçayı indirin.\n3. Avuç içleriyle iterek başlangıç pozisyonuna gelin.",
    mistakes: "Omuzları öne doğru aşırı yuvarlamak."
  },

  // --- BACAK (LEGS - QUADS, HAMSTRINGS, GLUTES) ---
  {
    id: 30,
    name: "Barbell Back Squat",
    slug: "squat",
    muscle: ["Quadriceps", "Kalça", "Hamstring", "Core"],
    equipment: ["Barbell"],
    environment: ["gym"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 4,
    reps: "6-8",
    rest: "120 saniye",
    gif: "images/squat.gif",
    video: "videos/squat.mp4",
    description: "Bacak gelişiminin ve tüm vücut anabolik gücünün temel direğidir. Ön bacak ve kalçayı inşa eder.",
    tips: "Ağırlığı topuklara ve ayağın ortasına verin; dizlerin içeri çökmesine izin vermeyin, ayak parmakları yönünde açın.",
    execution: "1. Barı üst trapezlere oturtun, göğsü dik tutun.\n2. Kalçayı geriye ve aşağıya doğru indirerek çömelin.\n3. Uyluklar yere paralel olunca yeri iterek kalkın.",
    mistakes: "Dizlerin içe kaçması, topukların yerden kalkması, beli bükmek."
  },
  {
    id: 31,
    name: "Goblet Squat",
    slug: "goblet-squat",
    muscle: ["Quadriceps", "Kalça", "Core"],
    equipment: ["Dambıl", "Kettlebell"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/goblet-squat.gif",
    video: "videos/goblet-squat.mp4",
    description: "Dambıl veya kettlebell göğüste tutularak yapılan, form öğrenimi için mükemmel ve güvenli çömelme egzersizi.",
    tips: "Ağırlığı göğüs hizasında sıkı tutmak gövdenin dik kalmasına doğal olarak yardımcı olur.",
    execution: "1. Dambılı iki elle çene altında kadeh gibi tutun.\n2. Dizleri açarak dirsekler dizlerin içine değecek kadar inin.\n3. Topuklardan iterek dik konuma gelin.",
    mistakes: "Öne doğru yuvarlanmak."
  },
  {
    id: 32,
    name: "Bodyweight Squat (Havasız Çömelme)",
    slug: "bodyweight-squat",
    muscle: ["Quadriceps", "Kalça"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner"],
    type: "endurance",
    sets: 3,
    reps: "15-20",
    rest: "60 saniye",
    gif: "images/bodyweight-squat.gif",
    video: "videos/bodyweight-squat.mp4",
    description: "Ekipmansız ev ve açık hava için ideal çömelme hareketi.",
    tips: "Kolları öne uzatarak denge sağlayabilirsiniz.",
    execution: "1. Ayaklar omuz genişliğinde açık durun.\n2. Sandalyeye oturur gibi geriye çömelin.\n3. Ayak tabanları tam temas halindeyken doğrulun.",
    mistakes: "Dizleri aşırı öne kaydırıp topukları kaldırmak."
  },
  {
    id: 33,
    name: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    muscle: ["Quadriceps", "Kalça", "Hamstring"],
    equipment: ["Dambıl", "Bench", "Ekipmansız"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "8-10",
    rest: "75 saniye",
    gif: "images/bulgarian-split-squat.gif",
    video: "videos/bulgarian-split-squat.mp4",
    description: "Bir ayak sehpaya dayalı tek bacak çömelme; bacak kuvvet dengesizliklerini çözen en acımasız ve etkili harekettir.",
    tips: "Ön bacağa odaklanın; gövdeyi hafif öne eğmek kalça aktivasyonunu artırır.",
    execution: "1. Arka ayağı sehpaya parmak ucuyla yerleştirin.\n2. Ön diz 90 derece olana kadar dikey şekilde inin.\n3. Ön ayağın topuğundan kuvvet alarak doğrulun.",
    mistakes: "Ön ayağı sehpaya çok yakın koyup diz eklemine baskı yapmak."
  },
  {
    id: 34,
    name: "Romanian Deadlift (RDL)",
    slug: "romanian-deadlift",
    muscle: ["Hamstring", "Kalça", "Alt Sırt"],
    equipment: ["Barbell", "Dambıl"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "75 saniye",
    gif: "images/romanian-deadlift.gif",
    video: "videos/romanian-deadlift.mp4",
    description: "Kalçanın geriye itilmesiyle arka bacak ve glute liflerini derinlemesine esneten mükemmel egzersiz.",
    tips: "Dizleri çok az bükülü kilitleyin; hareketi dizden değil kalçayı geriye iterek (hip hinge) yapın.",
    execution: "1. Barı veya dambılları bacak önünde tutun.\n2. Kalçayı geriye iterek kaval kemiği ortasına kadar ağırlığı indirin.\n3. Arka bacakta gerginlik hissedince kalçayı sıkarak kalkın.",
    mistakes: "Sırtı kamburlaştırmak, dizleri aşırı büküp normal squat'a çevirmek."
  },
  {
    id: 35,
    name: "Walking Lunges (Yürüyüş Lunge)",
    slug: "walking-lunges",
    muscle: ["Quadriceps", "Kalça", "Hamstring"],
    equipment: ["Dambıl", "Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/lunges.gif",
    video: "videos/lunges.mp4",
    description: "Adım atarak yapılan bacak ve kalça egzersizi; kondisyon ve dengeyi aynı anda artırır.",
    tips: "Her adımda her iki dizin de yaklaşık 90 derece büküldüğünden emin olun.",
    execution: "1. Öne büyük bir adım atın.\n2. Arka diz yere hafifçe değene kadar inin.\n3. Öndeki ayağın topuğundan iterek bir sonraki adıma geçin.",
    mistakes: "Kısa adımlar atıp öndeki dizin ayak ucunu aşırı geçmesi."
  },
  {
    id: 36,
    name: "Leg Press",
    slug: "leg-press",
    muscle: ["Quadriceps", "Kalça"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 4,
    reps: "10-12",
    rest: "90 saniye",
    gif: "images/leg-press.gif",
    video: "videos/leg-press.mp4",
    description: "Makinede platformu ayaklarla itme; bele yük bindirmeden yüksek bacak hacmi sağlar.",
    tips: "Ayakları platformun ortasına omuz genişliğinde yerleştirin; tepe noktada dizleri asla kilitlemeyin.",
    execution: "1. Sırtı tam yaslayıp oturun, emniyeti açın.\n2. Dizler 90 dereceye gelene kadar ağırlığı indirin.\n3. Dizleri kilitlemeden kontrollüce yukarı itin.",
    mistakes: "Dizleri tepede tam kilitlemek (eklem hasarı), kalçayı koltuktan kaldırmak."
  },
  {
    id: 37,
    name: "Leg Extension",
    slug: "leg-extension",
    muscle: ["Quadriceps"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/leg-extension.gif",
    video: "videos/leg-extension.mp4",
    description: "Oturarak ön bacak uzatma hareketi; quad kaslarını saf izolasyonla yakar.",
    tips: "Tepe noktada quadriceps kasınızı 1 saniye kaskatı sıkın.",
    execution: "1. Pedi kaval kemiğinin alt kısmına ayarlayın.\n2. Bacakları düz konuma getirene kadar kaldırın.\n3. Yavaşça başlangıca indirin.",
    mistakes: "Ağırlığı savurarak kaldırmak."
  },
  {
    id: 38,
    name: "Lying Leg Curl",
    slug: "leg-curl",
    muscle: ["Hamstring"],
    equipment: ["Kablo/Makine"],
    environment: ["gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/leg-curl.gif",
    video: "videos/leg-curl.mp4",
    description: "Yüzüstü yatarak bacakları bükme; arka bacak kaslarını doğrudan izole eder.",
    tips: "Kalçanızı sehpadan kaldırmayın; hareketi diz arkası kaslarıyla çekin.",
    execution: "1. Pedi topukların hemen üzerine yerleştirin.\n2. Bacakları kalçaya doğru bükün.\n3. Tepe noktada sıkıp yavaşça indirin.",
    mistakes: "Belden kuvvet alıp kalçayı havaya kaldırmak."
  },
  {
    id: 39,
    name: "Glute Bridge (Kalça Köprüsü)",
    slug: "glute-bridge",
    muscle: ["Kalça", "Hamstring"],
    equipment: ["Ekipmansız", "Dambıl"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/glute-bridge.gif",
    video: "videos/glute-bridge.mp4",
    description: "Yerde sırtüstü kalçayı yukarı kaldırma; kalça kaslarını uyandırmak ve şekillendirmek için harikadır.",
    tips: "Tepe noktada kalçayı 2 saniye sıkın, beli aşırı bükmeyin.",
    execution: "1. Sırtüstü uzanın, dizleri büküp ayakları yere basın.\n2. Topuklardan güç alarak kalçayı yukarı kaldırın.\n3. Kalça kaslarını sıkarak kontrollü indirin.",
    mistakes: "Hareketi bel kaslarıyla yapmak."
  },

  // --- BALDIR (CALVES) ---
  {
    id: 40,
    name: "Standing Calf Raise",
    slug: "standing-calf-raise",
    muscle: ["Baldır"],
    equipment: ["Dambıl", "Makine", "Ekipmansız"],
    environment: ["gym", "home", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "hypertrophy",
    sets: 4,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/standing-calf-raise.gif",
    video: "videos/standing-calf-raise.mp4",
    description: "Parmak uçlarında yükselerek baldır (gastrocnemius) kaslarını hedefleyen temel hareket.",
    tips: "Dip noktada topukların aşağı inerek derin esnemesini sağlayın, tepede parmak ucunda 1 saniye bekleyin.",
    execution: "1. Bir basamak kenarında parmak ucunda durun.\n2. Topukları aşağı indirip derin esneyin.\n3. Parmak ucunda maksimum yüksekliğe çıkıp sıkın.",
    mistakes: "Hızlı hızlı zıplayarak aşil tendonunun esnekliğinden faydalanmak (kas çalışmaz)."
  },
  {
    id: 41,
    name: "Seated Calf Raise",
    slug: "seated-calf-raise",
    muscle: ["Baldır"],
    equipment: ["Makine", "Dambıl"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/seated-calf-raise.gif",
    video: "videos/seated-calf-raise.mp4",
    description: "Dizler 90 derece bükülüyken yapılan, baldırın derin kası soleus'u büyüten egzersiz.",
    tips: "Dizlerin bükük olması gastrocnemius'u devre dışı bırakır ve baldırın genişliğini artırır.",
    execution: "1. Oturun, dambılları veya pedi diz üstüne koyun.\n2. Parmak uçlarıyla ağırlığı yukarı itin.\n3. Yavaşça topukları aşağıya indirin.",
    mistakes: "Yarım hareket yapmak."
  },

  // --- KARIN / CORE ---
  {
    id: 42,
    name: "Plank",
    slug: "plank",
    muscle: ["Karın", "Core", "Omuz"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "endurance",
    sets: 3,
    reps: "45-60 sn",
    rest: "45 saniye",
    gif: "images/plank.gif",
    video: "videos/plank.mp4",
    description: "Statik merkez bölge stabilizasyonu; tüm korse kaslarını demir gibi sağlamlaştırır.",
    tips: "Gövdeniz başınızdan topuklarınıza kadar tek bir cetvel gibi olmalıdır. Karın ve kalçayı sıkın.",
    execution: "1. Ön kollar ve ayak parmak uçları üzerinde durun.\n2. Beli aşağı düşürmeden karnı içeride tutun.\n3. Belirlenen süre boyunca derin nefes alarak pozisyonu koruyun.",
    mistakes: "Kalçayı havaya dikmek veya beli aşağı sarkıtmak."
  },
  {
    id: 43,
    name: "Hanging Leg Raise",
    slug: "hanging-leg-raise",
    muscle: ["Karın"],
    equipment: ["Barfiks demiri"],
    environment: ["gym", "outdoor", "home"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/hanging-leg-raise.gif",
    video: "videos/hanging-leg-raise.mp4",
    description: "Barfiks barında asılıyken bacakları yukarı kaldırma; alt karın ve merkez bölge için en güçlü harekettir.",
    tips: "Sallanmamak için karın kaslarınızı kilitleyin; kalçayı hafif öne yuvarlayarak karnı kıvırın.",
    execution: "1. Barfiks barında kollar gergin asılın.\n2. Sallanmadan bacakları yere paralel olana kadar kaldırın.\n3. Kontrollü şekilde başlangıca indirin.",
    mistakes: "Gövdeyi öne arkaya sallayarak ivme kullanmak."
  },
  {
    id: 44,
    name: "Lying Floor Leg Raise",
    slug: "lying-leg-raise",
    muscle: ["Karın"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "12-15",
    rest: "45 saniye",
    gif: "images/lying-leg-raise.gif",
    video: "videos/lying-leg-raise.mp4",
    description: "Yere sırtüstü uzanıp bacakları kaldırma; pratik ve etkili alt karın çalıştırıcı.",
    tips: "Bel boşluğunuzun yerden kalkmamasına dikkat edin; ellerinizi kalçanın yanına destek yapabilirsiniz.",
    execution: "1. Yere sırtüstü yatın.\n2. Bacakları 90 dereceye kadar düz kaldırın.\n3. Topuklar yere değmeden önce durup tekrar kaldırın.",
    mistakes: "Bacaklar inerken belin yay gibi havaya kalkması."
  },
  {
    id: 45,
    name: "Russian Twist",
    slug: "russian-twist",
    muscle: ["Karın", "Yan Karın"],
    equipment: ["Ekipmansız", "Dambıl"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "endurance",
    sets: 3,
    reps: "20 tekrar",
    rest: "45 saniye",
    gif: "images/russian-twist.gif",
    video: "videos/russian-twist.mp4",
    description: "Oturarak gövdeyi sağa sola döndürme; oblik (yan karın) kaslarını ve rotasyonel kuvveti hedefler.",
    tips: "Sadece kolları değil, göğüs kafesini ve omuzları tamamen yana çevirin.",
    execution: "1. Dizleri büküp ayakları hafif kaldırarak V pozisyonu alın.\n2. Gövdeyi sağa ve sola kontrollü şekilde çevirin.\n3. Karın kaslarını sürekli gergin tutun.",
    mistakes: "Sadece elleri sağa sola sallayıp gövdeyi döndürmemek."
  },
  {
    id: 46,
    name: "Abdominal Crunch (Mekik)",
    slug: "crunch",
    muscle: ["Karın"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner"],
    type: "hypertrophy",
    sets: 3,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/crunch.gif",
    video: "videos/crunch.mp4",
    description: "Üst karın kaslarını izole eden klasik ve güvenli kıvrılma hareketi.",
    tips: "Tam oturmayın; sadece kürek kemiklerini yerden 5-10 cm kaldırıp karnı sıkın.",
    execution: "1. Sırtüstü uzanın, dizleri bükün.\n2. Elleri baş arkasına hafifçe koyun (boynu çekmeyin).\n3. Karın kaslarını sıkarak omuzları yerden kaldırın.",
    mistakes: "Ellerle boynu öne doğru çekip omurlara baskı uygulamak."
  },
  {
    id: 47,
    name: "Mountain Climber (Dağ Tırmanışı)",
    slug: "mountain-climber",
    muscle: ["Karın", "Kardiyo", "Omuz"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "cardio",
    sets: 3,
    reps: "30-40 sn",
    rest: "45 saniye",
    gif: "images/mountain-climber.gif",
    video: "videos/mountain-climber.mp4",
    description: "Plank pozisyonunda dizleri sırayla göğse çekme; hem karın kaslarını hem de kardiyovasküler sistemi ateşler.",
    tips: "Kalçayı çok yukarı kaldırmayın, ritmik ve seri tempoyu koruyun.",
    execution: "1. Şınav pozisyonu alın.\n2. Sağ dizi göğse çekip hızla geri itin.\n3. Sol dizi çekip koşar adım temposunda sürdürün.",
    mistakes: "Kalçayı aşırı zıplatmak."
  },

  // --- KARDİYO & KONDİSYON ---
  {
    id: 48,
    name: "Jump Rope (İp Atlama)",
    slug: "jump-rope",
    muscle: ["Kardiyo", "Baldır", "Omuz"],
    equipment: ["İp", "Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "cardio",
    sets: 3,
    reps: "2-3 dakika",
    rest: "60 saniye",
    gif: "images/jump-rope.gif",
    video: "videos/jump-rope.mp4",
    description: "Yüksek kalori yakımı, ayak koordinasyonu ve çeviklik sağlayan klasik kardiyo egzersizi.",
    tips: "Parmak ucunda hafifçe sıçrayın, ipi omuzlardan değil bileklerden çevirin.",
    execution: "1. İpi tutun, dirsekleri gövdeye yakın tutun.\n2. Parmak uçlarında zeminden birkaç santim zıplayarak ipi altınızdan geçirin.",
    mistakes: "Topukların üzerine sert iniş yapmak."
  },
  {
    id: 49,
    name: "Running / Jogging (Koşu)",
    slug: "running",
    muscle: ["Kardiyo", "Bacak"],
    equipment: ["Ekipmansız"],
    environment: ["outdoor", "gym"],
    level: ["beginner", "intermediate", "advanced"],
    type: "cardio",
    sets: 1,
    reps: "15-25 dakika",
    rest: "Tempo bazlı",
    gif: "images/running.gif",
    video: "videos/running.mp4",
    description: "Yağ yakımı, kalp damar sağlığı ve dayanıklılık için açık hava veya koşu bandı çalışması.",
    tips: "Adımları ayağın ortasıyla yere basın, kollar 90 derece bükülü ritmik hareket etsin.",
    execution: "1. 5 dk hafif yürüyüşle ısının.\n2. Hedef nabız aralığında tempolu koşuya geçin.\n3. 3 dk soğuma yürüyüşü ile bitirin.",
    mistakes: "Aşırı hızlı başlayıp erken tükenmek."
  },
  {
    id: 50,
    name: "Burpees",
    slug: "burpees",
    muscle: ["Kardiyo", "Göğüs", "Bacak", "Core"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "cardio",
    sets: 3,
    reps: "10-15",
    rest: "60 saniye",
    gif: "images/burpees.gif",
    video: "videos/burpees.mp4",
    description: "Çömelme, şınav ve sıçramayı birleştiren tam vücut metabolik yağ yakım canavarı.",
    tips: "Hareket geçişlerini akıcı yapın, yere inerken kontrollü olun.",
    execution: "1. Çömelip elleri yere koyun.\n2. Ayakları geriye fırlatıp şınav pozisyonuna geçin ve göğsü yere değdirin.\n3. Ayakları öne çekip elleri baş üstüne kaldırarak zıplayın.",
    mistakes: "Beli yere kontrolsüzce çarpmak."
  },
  {
    id: 51,
    name: "High Knees (Yüksek Diz Koşu)",
    slug: "high-knees",
    muscle: ["Kardiyo", "Karın", "Bacak"],
    equipment: ["Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "cardio",
    sets: 3,
    reps: "30-45 sn",
    rest: "45 saniye",
    gif: "images/high-knees.gif",
    video: "videos/high-knees.mp4",
    description: "Olduğun yerde dizleri göğüs hizasına kadar çekerek yapılan yoğun kardiyo.",
    tips: "Parmak uçlarında sekin, gövdeyi dik tutun.",
    execution: "1. Ayakta dik durun.\n2. Dizleri sırayla bel hizasına kadar çekerek koşun.\n3. Kolları tempoya eşlik edecek şekilde sallayın.",
    mistakes: "Gövdeyi geriye doğru aşırı yatırmak."
  },
  {
    id: 52,
    name: "Brisk Walking (Tempolu Yürüyüş)",
    slug: "brisk-walking",
    muscle: ["Kardiyo"],
    equipment: ["Ekipmansız"],
    environment: ["outdoor", "gym", "home"],
    level: ["beginner", "intermediate"],
    type: "cardio",
    sets: 1,
    reps: "20-30 dakika",
    rest: "Sürekli",
    gif: "images/walking.gif",
    video: "videos/walking.mp4",
    description: "Eklemlere sıfır darbe ile düşük yoğunluklu sabit tempo (LISS) yağ yakımı ve toparlanma yürüyüşü.",
    tips: "Konuşabileceğiniz ama şarkı söyleyemeyeceğiniz bir tempoda yürüyün.",
    execution: "1. Dik bir postürle tempolu yürümeye başlayın.\n2. Kollarınızı ritmik olarak sallayın.",
    mistakes: "Yavaş ve dağınık adımlarla yürümek."
  },
  // --- YENİ EKİPMAN ODAKLI EGZERSİZLER ---
  {
    id: 53,
    name: "Ab Wheel Rollout (Karın Tekerleği)",
    slug: "ab-wheel-rollout",
    muscle: ["Karın", "Core", "Omuz", "Lat"],
    equipment: ["Karın Tekerleği"],
    environment: ["home", "gym"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "8-12",
    rest: "60 saniye",
    gif: "images/ab-rollout.gif",
    video: "videos/ab-rollout.mp4",
    description: "Dizler üzerinde karın tekerleğini öne doğru sürme; merkez bölgeyi (core) olağanüstü güçlendirir.",
    tips: "Beli aşağı çökertmeyin; karın kaslarınızı kilitli tutarak kontrollü uzanın ve geri çekin.",
    execution: "1. Dizlerinizin üzerine mat yerleştirin, tekerleği kavrayın.\n2. Yavaşça öne doğru yuvarlanarak uzanın.\n3. Karın kaslarınızı sıkarak başlangıç konumuna dönün.",
    mistakes: "Bel omurlarını aşağı sarkıtmak (omurga baskısı)."
  },
  {
    id: 54,
    name: "Kettlebell Swing (Girya Salınımı)",
    slug: "kettlebell-swing",
    muscle: ["Kalça", "Hamstring", "Core", "Kardiyo"],
    equipment: ["Kettlebell"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "cardio",
    sets: 4,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/kettlebell-swing.gif",
    video: "videos/kettlebell-swing.mp4",
    description: "Kalçanın patlayıcı itişiyle yapılan dinamik yağ yakım ve arka zincir güçlendirici hareket.",
    tips: "Kolları değil kalçayı kullanın; squat gibi değil, kalçayı geriye iterek menteşe (hinge) hareketi yapın.",
    execution: "1. Kettlebell'i bacakların arasından arkaya doğru alın.\n2. Kalçayı patlayıcı şekilde öne iterek göğüs hizasına fırlatın.\n3. Ağırlığın ağırlıksız kaldığı tepe noktada kalçayı sıkın.",
    mistakes: "Hareketi omuz veya kollarla yukarı çekmeye çalışmak."
  },
  {
    id: 55,
    name: "EZ Bar Skull Crusher",
    slug: "ez-bar-skull-crusher",
    muscle: ["Triceps"],
    equipment: ["EZ Bar", "Ağırlık Sehpası"],
    environment: ["gym", "home"],
    level: ["intermediate", "advanced"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/ez-skull-crusher.gif",
    video: "videos/ez-skull-crusher.mp4",
    description: "EZ barın açılı tutuşu ile bilekleri koruyarak arka kolu izole eden klasik egzersiz.",
    tips: "Açılı tutuş sayesinde bilek stresini sıfırlar ve triceps uzun başını maksimum çalıştırır.",
    execution: "1. Sehpaya uzanın, EZ barı dar açıdan kavrayın.\n2. Dirsekleri sabit tutarak barı alnın hemen gerisine indirin.\n3. Sadece ön kolları uzatarak tepeye itin.",
    mistakes: "Dirsekleri iki yana açmak."
  },
  {
    id: 56,
    name: "EZ Bar Preacher Curl (Scott Curl)",
    slug: "ez-bar-preacher-curl",
    muscle: ["Biceps", "Ön kol"],
    equipment: ["EZ Bar", "Ağırlık Sehpası"],
    environment: ["gym", "home"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "10-12",
    rest: "60 saniye",
    gif: "images/preacher-curl.gif",
    video: "videos/preacher-curl.mp4",
    description: "Destekli sehpa üzerinde pazu kasını tamamen izole ederek hile yapmayı engelleyen egzersiz.",
    tips: "Kolun alt kısmını sehpaya tam yapıştırın, tepe noktada pazuyu sıkın.",
    execution: "1. Kollarınızı preacher sehpasına yaslayın.\n2. Barı çene hizasına doğru kıvırın.\n3. Kontrollü şekilde negatif fazda indirin.",
    mistakes: "Aşağıda dirsekleri aşırı gerip kilitlemek."
  },
  {
    id: 57,
    name: "TRX Suspension Row (TRX Çekiş)",
    slug: "trx-row",
    muscle: ["Sırt", "Biceps", "Core"],
    equipment: ["TRX / Süspansiyon Kayışı"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "12-15",
    rest: "60 saniye",
    gif: "images/trx-row.gif",
    video: "videos/trx-row.mp4",
    description: "Askı kayışları kullanılarak kendi vücut ağırlığınızla yapılan eklem dostu sırt çekişi.",
    tips: "Ayakları ne kadar öne koyarsanız hareket o kadar zorlaşır; vücut tahta gibi düz kalmalıdır.",
    execution: "1. TRX tutacaklarını kavrayıp geriye yaslanın.\n2. Kürek kemiklerini sıkarak göğsünüzü tutacaklara doğru çekin.\n3. Yavaşça başlangıç açısına inin.",
    mistakes: "Kalçayı geriye düşürüp beli bükmek."
  },
  {
    id: 58,
    name: "Mini Loop Band Clamshell (İstiridye)",
    slug: "mini-band-clamshell",
    muscle: ["Kalça"],
    equipment: ["Mini Loop Band", "Egzersiz Matı"],
    environment: ["home", "gym", "outdoor"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/mini-band-clamshell.gif",
    video: "videos/mini-band-clamshell.mp4",
    description: "Dizlerin hemen üzerine takılan mini lastik bant ile gluteus medius (yan kalça) aktivasyonu.",
    tips: "Kalça stabilitesini ve diz sağlığını korumak için en etkili aktivasyon hareketidir.",
    execution: "1. Yan yatın, dizleri 90 derece bükün ve bandı takın.\n2. Ayakları bir arada tutarak üstteki dizi yukarı açın.\n3. Kalçayı sıkıp yavaşça indirin.",
    mistakes: "Gövdeyi geriye doğru devirmek."
  },
  {
    id: 59,
    name: "Swiss Ball Crunch (Pilates Topu Mekik)",
    slug: "swiss-ball-crunch",
    muscle: ["Karın"],
    equipment: ["Pilates Topu", "Egzersiz Matı"],
    environment: ["home", "gym"],
    level: ["beginner", "intermediate"],
    type: "hypertrophy",
    sets: 3,
    reps: "15-20",
    rest: "45 saniye",
    gif: "images/swiss-ball-crunch.gif",
    video: "videos/swiss-ball-crunch.mp4",
    description: "Pilates topu üzerinde yapılan karın kıvrılması; omurga eğrisi sayesinde tam esneme ve kasılma sağlar.",
    tips: "Geriye doğru uzanarak karın kaslarını derin esnetin, ardından yukarı kıvrılın.",
    execution: "1. Belinizi topun kavisli yüzeyine yerleştirin.\n2. Karın kaslarını gererek geriye yaslanın.\n3. Nefes vererek öne doğru kıvrılın ve karnı sıkın.",
    mistakes: "Top üzerinden kaymak veya boynu zorlamak."
  },
  {
    id: 60,
    name: "Weighted Push Up (Ağırlık Yelekli Şınav)",
    slug: "weighted-push-up",
    muscle: ["Göğüs", "Triceps", "Ön Omuz"],
    equipment: ["Ağırlık Yeleği", "Ekipmansız"],
    environment: ["home", "gym", "outdoor"],
    level: ["intermediate", "advanced"],
    type: "strength",
    sets: 3,
    reps: "8-12",
    rest: "75 saniye",
    gif: "images/weighted-pushup.gif",
    video: "videos/weighted-pushup.mp4",
    description: "Ağırlık yeleği giyilerek yapılan, göğüs ve triceps kuvvetini katlayan ileri seviye şınav.",
    tips: "Klasik şınav hafif geldiğinde aşırı kas uyarımı sağlamak için mükemmeldir.",
    execution: "1. Ağırlık yeleğini sıkıca bağlayın.\n2. Göğsünüz yere yaklaşana kadar kontrollü inin.\n3. Patlayıcı güçle yukarı itin.",
    mistakes: "Beli çökertmek."
  }
];

// Tüm egzersizler için temsilî görsel yolu (placeholder image) tanımlaması
EXERCISE_DATABASE.forEach(ex => {
  if (!ex.image) {
    ex.image = `images/${ex.slug}.jpg`;
  }
});
